// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MUSICUI_H
#define UI_MUSICUI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_musicui
extern void ui_musicui_screen_init(void);
extern void ui_musicui_screen_destroy(void);
extern void ui_event_musicui(lv_event_t * e);
extern lv_obj_t * ui_musicui;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_xiayishou;
extern lv_obj_t * ui_shangyishou;
extern lv_obj_t * ui_Slider1;
extern void ui_event_yinl(lv_event_t * e);
extern lv_obj_t * ui_yinl;
extern lv_obj_t * ui_bofangsuij;
extern lv_obj_t * ui_geci;
extern lv_obj_t * ui_geshou;
extern lv_obj_t * ui_geming;
extern lv_obj_t * ui_jindu1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_wifi1;
extern lv_obj_t * ui_wifi2;
extern lv_obj_t * ui_bofangliebiao;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_fengmian;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Slider2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

