// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_musicui = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_xiayishou = NULL;
lv_obj_t * ui_shangyishou = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_yinl = NULL;
lv_obj_t * ui_bofangsuij = NULL;
lv_obj_t * ui_geci = NULL;
lv_obj_t * ui_geshou = NULL;
lv_obj_t * ui_geming = NULL;
lv_obj_t * ui_jindu1 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_wifi1 = NULL;
lv_obj_t * ui_wifi2 = NULL;
lv_obj_t * ui_bofangliebiao = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_fengmian = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Slider2 = NULL;
// event funtions
void ui_event_musicui(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_timeui, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_timeui_screen_init);
    }
}

void ui_event_yinl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        tanchuon_Animation(ui_Panel2, 0);
    }
}

// build funtions

void ui_musicui_screen_init(void)
{
    ui_musicui = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_musicui, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_musicui, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_musicui, lv_color_hex(0x121417), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_musicui, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_musicui);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 240);
    lv_obj_set_y(ui_time, -212);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "21:38");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_musicui);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 64);
    lv_obj_set_x(ui_Button1, -20);
    lv_obj_set_y(ui_Button1, 166);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_bf1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_musicui);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);

    ui_xiayishou = lv_btn_create(ui_musicui);
    lv_obj_set_width(ui_xiayishou, 80);
    lv_obj_set_height(ui_xiayishou, 64);
    lv_obj_set_x(ui_xiayishou, 90);
    lv_obj_set_y(ui_xiayishou, 166);
    lv_obj_set_align(ui_xiayishou, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xiayishou, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_xiayishou, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_xiayishou, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_xiayishou, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_xiayishou, &ui_img_xiayige_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shangyishou = lv_btn_create(ui_musicui);
    lv_obj_set_width(ui_shangyishou, 80);
    lv_obj_set_height(ui_shangyishou, 64);
    lv_obj_set_x(ui_shangyishou, -130);
    lv_obj_set_y(ui_shangyishou, 166);
    lv_obj_set_align(ui_shangyishou, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shangyishou, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_shangyishou, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_shangyishou, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shangyishou, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_shangyishou, &ui_img_2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_musicui);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 418);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 123);
    lv_obj_set_y(ui_Slider1, 52);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x34383D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x38B7A5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_yinl = lv_btn_create(ui_musicui);
    lv_obj_set_width(ui_yinl, 100);
    lv_obj_set_height(ui_yinl, 50);
    lv_obj_set_x(ui_yinl, -280);
    lv_obj_set_y(ui_yinl, 166);
    lv_obj_set_align(ui_yinl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yinl, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_yinl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_yinl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yinl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_yinl, &ui_img_yl_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bofangsuij = lv_btn_create(ui_musicui);
    lv_obj_set_width(ui_bofangsuij, 90);
    lv_obj_set_height(ui_bofangsuij, 50);
    lv_obj_set_x(ui_bofangsuij, 220);
    lv_obj_set_y(ui_bofangsuij, 166);
    lv_obj_set_align(ui_bofangsuij, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bofangsuij, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bofangsuij, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bofangsuij, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bofangsuij, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_bofangsuij, &ui_img_shunxu_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_geci = lv_label_create(ui_musicui);
    lv_obj_set_width(ui_geci, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_geci, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_geci, 100);
    lv_obj_set_y(ui_geci, -11);
    lv_obj_set_align(ui_geci, LV_ALIGN_CENTER);
    lv_label_set_text(ui_geci, "雨下整夜，我的爱溢出就像雨水");
    lv_obj_set_style_text_color(ui_geci, lv_color_hex(0xF4EFE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_geci, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_geci, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_geshou = lv_label_create(ui_musicui);
    lv_obj_set_width(ui_geshou, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_geshou, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_geshou, 95);
    lv_obj_set_y(ui_geshou, -68);
    lv_obj_set_align(ui_geshou, LV_ALIGN_CENTER);
    lv_label_set_text(ui_geshou, "周杰伦");
    lv_obj_set_style_text_color(ui_geshou, lv_color_hex(0x38B7A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_geshou, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_geshou, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_geming = lv_label_create(ui_musicui);
    lv_obj_set_width(ui_geming, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_geming, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_geming, 95);
    lv_obj_set_y(ui_geming, -130);
    lv_obj_set_align(ui_geming, LV_ALIGN_CENTER);
    lv_label_set_text(ui_geming, "七里香");
    lv_obj_set_style_text_color(ui_geming, lv_color_hex(0xF4EFE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_geming, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_geming, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jindu1 = lv_label_create(ui_musicui);
    lv_obj_set_width(ui_jindu1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jindu1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_jindu1, -84);
    lv_obj_set_y(ui_jindu1, 85);
    lv_obj_set_align(ui_jindu1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jindu1, "1:24");
    lv_obj_set_style_text_color(ui_jindu1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_jindu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_jindu1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_musicui);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 314);
    lv_obj_set_y(ui_Label7, 85);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "3:56");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi1 = lv_img_create(ui_musicui);
    lv_img_set_src(ui_wifi1, &ui_img_1515518950);
    lv_obj_set_width(ui_wifi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi1, 343);
    lv_obj_set_y(ui_wifi1, -214);
    lv_obj_set_align(ui_wifi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifi2 = lv_img_create(ui_musicui);
    lv_img_set_src(ui_wifi2, &ui_img_wifioffoutlined_png);
    lv_obj_set_width(ui_wifi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi2, 343);
    lv_obj_set_y(ui_wifi2, -212);
    lv_obj_set_align(ui_wifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bofangliebiao = lv_imgbtn_create(ui_musicui);
    lv_imgbtn_set_src(ui_bofangliebiao, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1794949695, NULL);
    lv_imgbtn_set_src(ui_bofangliebiao, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_191345099, NULL);
    lv_obj_set_width(ui_bofangliebiao, 64);
    lv_obj_set_height(ui_bofangliebiao, 64);
    lv_obj_set_x(ui_bofangliebiao, 345);
    lv_obj_set_y(ui_bofangliebiao, 166);
    lv_obj_set_align(ui_bofangliebiao, LV_ALIGN_CENTER);

    ui_Panel1 = lv_obj_create(ui_musicui);
    lv_obj_set_width(ui_Panel1, 256);
    lv_obj_set_height(ui_Panel1, 256);
    lv_obj_set_x(ui_Panel1, -240);
    lv_obj_set_y(ui_Panel1, -46);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 256, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel1, &ui_img_vinyl_record_256_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fengmian = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_fengmian, &ui_img_1953031374);
    lv_obj_set_width(ui_fengmian, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fengmian, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fengmian, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fengmian, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fengmian, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_musicui);
    lv_obj_set_width(ui_Panel2, 25);
    lv_obj_set_height(ui_Panel2, 324);
    lv_obj_set_x(ui_Panel2, -369);
    lv_obj_set_y(ui_Panel2, -16);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Panel2);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 19);
    lv_obj_set_height(ui_Slider2, 323);
    lv_obj_set_x(ui_Slider2, -1);
    lv_obj_set_y(ui_Slider2, -2);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xA7A7AD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_yinl, ui_event_yinl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_musicui, ui_event_musicui, LV_EVENT_ALL, NULL);

}

void ui_musicui_screen_destroy(void)
{
    if(ui_musicui) lv_obj_del(ui_musicui);

    // NULL screen variables
    ui_musicui = NULL;
    ui_time = NULL;
    ui_Button1 = NULL;
    ui_Label2 = NULL;
    ui_xiayishou = NULL;
    ui_shangyishou = NULL;
    ui_Slider1 = NULL;
    ui_yinl = NULL;
    ui_bofangsuij = NULL;
    ui_geci = NULL;
    ui_geshou = NULL;
    ui_geming = NULL;
    ui_jindu1 = NULL;
    ui_Label7 = NULL;
    ui_wifi1 = NULL;
    ui_wifi2 = NULL;
    ui_bofangliebiao = NULL;
    ui_Panel1 = NULL;
    ui_fengmian = NULL;
    ui_Panel2 = NULL;
    ui_Slider2 = NULL;

}
