// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TIMEUI_H
#define UI_TIMEUI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_timeui
extern void ui_timeui_screen_init(void);
extern void ui_timeui_screen_destroy(void);
extern void ui_event_timeui(lv_event_t * e);
extern lv_obj_t * ui_timeui;
extern lv_obj_t * ui_data;
extern lv_obj_t * ui_week;
extern lv_obj_t * ui_timelable;
extern lv_obj_t * ui_data1;
extern lv_obj_t * ui_wea;
extern lv_obj_t * ui_weaicon;
extern lv_obj_t * ui_weatext;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_wendu;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_wenduicon;
extern lv_obj_t * ui_shiduicon;
extern lv_obj_t * ui_shidutext;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_SHIJIAN;
extern lv_obj_t * ui_events;
extern lv_obj_t * ui_musicpa;
extern lv_obj_t * ui_gemingxinxi;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_elseev;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

