// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_timeui = NULL;
lv_obj_t * ui_data = NULL;
lv_obj_t * ui_week = NULL;
lv_obj_t * ui_timelable = NULL;
lv_obj_t * ui_data1 = NULL;
lv_obj_t * ui_wea = NULL;
lv_obj_t * ui_weaicon = NULL;
lv_obj_t * ui_weatext = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_wendu = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_wenduicon = NULL;
lv_obj_t * ui_shiduicon = NULL;
lv_obj_t * ui_shidutext = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_SHIJIAN = NULL;
lv_obj_t * ui_events = NULL;
lv_obj_t * ui_musicpa = NULL;
lv_obj_t * ui_gemingxinxi = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_elseev = NULL;
// event funtions
void ui_event_timeui(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_musicui, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_musicui_screen_init);
    }
}

// build funtions

void ui_timeui_screen_init(void)
{
    ui_timeui = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_timeui, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timeui, lv_color_hex(0x1D1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeui, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_data = lv_obj_create(ui_timeui);
    lv_obj_set_width(ui_data, 276);
    lv_obj_set_height(ui_data, 295);
    lv_obj_set_x(ui_data, 0);
    lv_obj_set_y(ui_data, -77);
    lv_obj_set_align(ui_data, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_data, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_data, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_data, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_data, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_data, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week = lv_label_create(ui_data);
    lv_obj_set_width(ui_week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_week, 0);
    lv_obj_set_y(ui_week, 35);
    lv_obj_set_align(ui_week, LV_ALIGN_CENTER);
    lv_label_set_text(ui_week, "星期天");
    lv_obj_set_style_text_color(ui_week, lv_color_hex(0xFF00C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_week, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_week, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timelable = lv_label_create(ui_data);
    lv_obj_set_width(ui_timelable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timelable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timelable, 0);
    lv_obj_set_y(ui_timelable, -73);
    lv_obj_set_align(ui_timelable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timelable, "21:38");
    lv_obj_set_style_text_color(ui_timelable, lv_color_hex(0xFF00C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timelable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timelable, &ui_font_Font4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_data1 = lv_label_create(ui_data);
    lv_obj_set_width(ui_data1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_data1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_data1, 0);
    lv_obj_set_y(ui_data1, 123);
    lv_obj_set_align(ui_data1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_data1, "2026年6月10日");
    lv_obj_set_style_text_color(ui_data1, lv_color_hex(0xFF00C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_data1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_data1, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wea = lv_obj_create(ui_timeui);
    lv_obj_set_width(ui_wea, 200);
    lv_obj_set_height(ui_wea, 234);
    lv_obj_set_x(ui_wea, -268);
    lv_obj_set_y(ui_wea, -95);
    lv_obj_set_align(ui_wea, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wea, lv_color_hex(0x181C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wea, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weaicon = lv_img_create(ui_wea);
    lv_img_set_src(ui_weaicon, &ui_img_1650588022);
    lv_obj_set_width(ui_weaicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weaicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weaicon, 0);
    lv_obj_set_y(ui_weaicon, -48);
    lv_obj_set_align(ui_weaicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weaicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weaicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatext = lv_label_create(ui_wea);
    lv_obj_set_width(ui_weatext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatext, 0);
    lv_obj_set_y(ui_weatext, 33);
    lv_obj_set_align(ui_weatext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatext, "雨");
    lv_obj_set_style_text_color(ui_weatext, lv_color_hex(0xEDF50C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatext, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_wea);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, 83);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "成都");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xEAF208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_obj_create(ui_timeui);
    lv_obj_set_width(ui_temp, 150);
    lv_obj_set_height(ui_temp, 144);
    lv_obj_set_x(ui_temp, -268);
    lv_obj_set_y(ui_temp, 134);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wendu = lv_label_create(ui_temp);
    lv_obj_set_width(ui_wendu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wendu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wendu, 10);
    lv_obj_set_y(ui_wendu, -25);
    lv_obj_set_align(ui_wendu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wendu, "32");
    lv_obj_set_style_text_color(ui_wendu, lv_color_hex(0xF70B45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wendu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wendu, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_temp);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 41);
    lv_obj_set_y(ui_Label8, -25);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "℃");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xF60841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wenduicon = lv_img_create(ui_temp);
    lv_img_set_src(ui_wenduicon, &ui_img_843332074);
    lv_obj_set_width(ui_wenduicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wenduicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wenduicon, -29);
    lv_obj_set_y(ui_wenduicon, -25);
    lv_obj_set_align(ui_wenduicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wenduicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wenduicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_shiduicon = lv_img_create(ui_temp);
    lv_img_set_src(ui_shiduicon, &ui_img_545021016);
    lv_obj_set_width(ui_shiduicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shiduicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shiduicon, -29);
    lv_obj_set_y(ui_shiduicon, 37);
    lv_obj_set_align(ui_shiduicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shiduicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_shiduicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_shidutext = lv_label_create(ui_temp);
    lv_obj_set_width(ui_shidutext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shidutext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shidutext, 10);
    lv_obj_set_y(ui_shidutext, 37);
    lv_obj_set_align(ui_shidutext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shidutext, "48");
    lv_obj_set_style_text_color(ui_shidutext, lv_color_hex(0x39BADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shidutext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shidutext, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_temp);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 41);
    lv_obj_set_y(ui_Label10, 37);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "%");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x39BADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_timeui);
    lv_obj_set_width(ui_Panel7, 214);
    lv_obj_set_height(ui_Panel7, 268);
    lv_obj_set_x(ui_Panel7, 264);
    lv_obj_set_y(ui_Panel7, -85);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x181C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -1);
    lv_obj_set_y(ui_Label11, -102);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "MEMO");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x4CF510), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SHIJIAN = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_SHIJIAN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SHIJIAN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SHIJIAN, -5);
    lv_obj_set_y(ui_SHIJIAN, -53);
    lv_obj_set_align(ui_SHIJIAN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SHIJIAN, "没有什么待干的事情");
    lv_obj_set_style_text_color(ui_SHIJIAN, lv_color_hex(0xF39104), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SHIJIAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SHIJIAN, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_events = lv_obj_create(ui_timeui);
    lv_obj_set_width(ui_events, 525);
    lv_obj_set_height(ui_events, 128);
    lv_obj_set_x(ui_events, 126);
    lv_obj_set_y(ui_events, 161);
    lv_obj_set_align(ui_events, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_events, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_events, lv_color_hex(0x181C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_events, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_events, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_events, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_musicpa = lv_obj_create(ui_events);
    lv_obj_set_width(ui_musicpa, 522);
    lv_obj_set_height(ui_musicpa, 128);
    lv_obj_set_align(ui_musicpa, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_musicpa, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_musicpa, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_musicpa, lv_color_hex(0x181C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_musicpa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_musicpa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_musicpa, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gemingxinxi = lv_label_create(ui_musicpa);
    lv_obj_set_width(ui_gemingxinxi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gemingxinxi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gemingxinxi, 0);
    lv_obj_set_y(ui_gemingxinxi, -31);
    lv_obj_set_align(ui_gemingxinxi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gemingxinxi, "七里香-周杰伦");
    lv_obj_set_style_text_color(ui_gemingxinxi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gemingxinxi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gemingxinxi, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_musicpa);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, 17);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "雨下整夜，我的爱溢出就像雨水");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Font5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elseev = lv_obj_create(ui_events);
    lv_obj_set_width(ui_elseev, 525);
    lv_obj_set_height(ui_elseev, 128);
    lv_obj_set_align(ui_elseev, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_elseev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_elseev, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_elseev, lv_color_hex(0x181C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_elseev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_elseev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_elseev, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_timeui, ui_event_timeui, LV_EVENT_ALL, NULL);

}

void ui_timeui_screen_destroy(void)
{
    if(ui_timeui) lv_obj_del(ui_timeui);

    // NULL screen variables
    ui_timeui = NULL;
    ui_data = NULL;
    ui_week = NULL;
    ui_timelable = NULL;
    ui_data1 = NULL;
    ui_wea = NULL;
    ui_weaicon = NULL;
    ui_weatext = NULL;
    ui_Label12 = NULL;
    ui_temp = NULL;
    ui_wendu = NULL;
    ui_Label8 = NULL;
    ui_wenduicon = NULL;
    ui_shiduicon = NULL;
    ui_shidutext = NULL;
    ui_Label10 = NULL;
    ui_Panel7 = NULL;
    ui_Label11 = NULL;
    ui_SHIJIAN = NULL;
    ui_events = NULL;
    ui_musicpa = NULL;
    ui_gemingxinxi = NULL;
    ui_Label14 = NULL;
    ui_elseev = NULL;

}
