// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_musicui.h"
#include "screens/ui_timeui.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * xuanzhuan_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * tanchuon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * tanhuioff_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bf1_png);    // assets/bf1.png
LV_IMG_DECLARE(ui_img_xiayige_png);    // assets/xiayige.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_yl_png);    // assets/yl.png
LV_IMG_DECLARE(ui_img_shunxu_png);    // assets/shunxu.png
LV_IMG_DECLARE(ui_img_1515518950);    // assets/wifi (1).png
LV_IMG_DECLARE(ui_img_wifioffoutlined_png);    // assets/wifiOffOutLined.png
LV_IMG_DECLARE(ui_img_1794949695);    // assets/24gf-playlistHeart4.png
LV_IMG_DECLARE(ui_img_191345099);    // assets/24gf-playlistHeart4 (1).png
LV_IMG_DECLARE(ui_img_vinyl_record_256_png);    // assets/vinyl_record_256.png
LV_IMG_DECLARE(ui_img_1953031374);    // assets/191931-17808311716aad_circle_128.png
LV_IMG_DECLARE(ui_img_1650588022);    // assets/晴天.png
LV_IMG_DECLARE(ui_img_843332074);    // assets/温度.png
LV_IMG_DECLARE(ui_img_545021016);    // assets/湿度.png
LV_IMG_DECLARE(ui_img_1256964955);    // assets/bg-play.png
LV_IMG_DECLARE(ui_img_shangyishou_png);    // assets/shangyishou.png
LV_IMG_DECLARE(ui_img_suiji_png);    // assets/suiji.png
LV_IMG_DECLARE(ui_img_1230129726);    // assets/启动.png
LV_IMG_DECLARE(ui_img_2051629593);    // assets/雨.png
LV_IMG_DECLARE(ui_img_1772208564);    // assets/多云.png
LV_IMG_DECLARE(ui_img_1840017345);    // assets/雷阵雨.png
LV_IMG_DECLARE(ui_img_1889690653);    // assets/雪.png
LV_IMG_DECLARE(ui_img_701658425);    // assets/雾.png
LV_IMG_DECLARE(ui_img_46488613);    // assets/雾霾.png
LV_IMG_DECLARE(ui_img_tech_music_background_800x480_png);    // assets/tech_music_background_800x480.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font3);
LV_FONT_DECLARE(ui_font_Font4);
LV_FONT_DECLARE(ui_font_Font5);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
